Fix to conflict in NixOS-WSL
Without this, raising error as follows

```plaintext
error: The option `system.build.installBootLoader' is defined multiple times while it's expected to be unique.
Only one bootloader can be enabled at a time. This requirement has not
been checked until NixOS 22.05. Earlier versions defaulted to the last
definition. Change your configuration to enable only one bootloader.

Definition values:
- In `/nix/store/z3vrsz16ypv60m2pp0gi7x7gpx40gfh1-source/nixos/modules/system/boot/loader/systemd-boot/systemd-boot.nix': <derivation install-systemd-boot.sh>
- In `/nix/store/43w25ycynlad7wpqc1qx9nzrr3vkiq7m-source/modules/wsl-distro.nix': "/nix/store/ysqx2xfzygv2rxl7nxnw48276z5ckppn-coreutils-9.5/bin/true"
Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```