Revert "gemini-cli-bin: 0.30.0 -> 0.31.0 (#1460)"
This reverts commit bcb6b4085f575c7e31cbe961f1970a650b908fd2.

This change caused CI failure:

```
building '/nix/store/i6iyp6qhhahpx5q7p5hp3703bfchbpqq-gemini-cli-bin-0.31.0.drv'...
error: Cannot build '/nix/store/i6iyp6qhhahpx5q7p5hp3703bfchbpqq-gemini-cli-bin-0.31.0.drv'.
       Reason: builder failed with exit code 126.
       Output paths:
         /nix/store/s4y30gzc2023k9mw5b2l2hgfk1rvh590-gemini-cli-bin-0.31.0
       Last 13 log lines:
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > no Makefile or custom buildPhase, doing nothing
       > Running phase: installPhase
       > Running phase: fixupPhase
       > shrinking RPATHs of ELF executables and libraries in /nix/store/s4y30gzc2023k9mw5b2l2hgfk1rvh590-gemini-cli-bin-0.31.0
       > checking for references to /build/ in /nix/store/s4y30gzc2023k9mw5b2l2hgfk1rvh590-gemini-cli-bin-0.31.0...
       > patching script interpreter paths in /nix/store/s4y30gzc2023k9mw5b2l2hgfk1rvh590-gemini-cli-bin-0.31.0
       > Running phase: installCheckPhase
       > /nix/store/lajqvvaxn87hc409wkxlzfq89ycf0pw4-stdenv-linux/setup: /nix/store/s4y30gzc2023k9mw5b2l2hgfk1rvh590-gemini-cli-bin-0.31.0/bin/gemini: /usr/bin/env: bad interpreter: No such file or directory
       For full logs, run:
         nix log /nix/store/i6iyp6qhhahpx5q7p5hp3703bfchbpqq-gemini-cli-bin-0.31.0.drv
```

It is an automerge trouble. I simply revert the commit for now.